### ISSUE TITLE
Add support for BLOB/CLOB types.

### ISSUE THREAD

**Issue by asavov** [r2dbc/r2dbc-h2#40]
Project main page states "This driver provides the following features: Read and write support for all data types except LOB types (e.g. BLOB, CLOB)"

What is the plan to support for org.h2.value.ValueLobDb?
- yes: great! when it might be expected?
- no: what are the obstacles/concerns?

My use-case is JPA_H2_Repo writes java.Map as CLOB/ValueLobDb and then it's not possible to read it by R2DBC_H2_Repo.

Thanks!

**Comment by mp911de** [comment]
Thanks for report.This relates to r2dbc/r2dbc-spi#41

The underlying issue is that we need to specify a proper API to work with large objects. 

> What is the plan to support for org.h2.value.ValueLobDb?

Eventually.

> * yes: great! when it might be expected?

I don't know. Perhaps by R2DBC 1.0 M8, maybe later.

> * no: what are the obstacles/concerns?

LOB's require a proper API that considers the event-driven nature of drivers. Please chime into the discussion at r2dbc/r2dbc-spi#41. We're happy to see how you would like to consume large objects (pseudo-code) or discuss even API proposals.

**Comment by asavov** [comment]
Mark, good to know that's already on your radar.

From a perspective of high-level Spring R2DBC project
  r2dbc.function.convert.EntityRowMapper<T> implements BiFunction<Row, RowMetadata, **Mono<T>**>
seems more aligned with r2dbc.function.RowsFetchSpec<T>

And then going down to r2dbc-spi.Row level maybe something similar to:
  Mono<XBuffer> getXLob(Object identifier)

My 2 cents:
- AlexS

**Comment by mp911de** [comment]
Thanks a lot for your suggestion. Can you mention your proposal in r2dbc/r2dbc-spi#41? Sounds like a decent extension. 

We should make sure to not require a `Publisher` creation for simple values, though, so an additional method along the lines of `mapLater(…)` could make sense there.

**Comment by gregturn** [comment]
See https://github.com/r2dbc/r2dbc-spi/pull/51 for details on the new SPI.
