### ISSUE TITLE
Capture suite of tests for various SQL operations to verify proper H2 API usage

### ISSUE THREAD

**Issue by gregturn** [r2dbc/r2dbc-h2#9]
`H2Statement.execute()` switches on whether or not an `INSERT` is being issues as to whether it uses `Session.update` vs. `Session.update`.

```java
private Flux<H2Result> execute(String sql) {
    if (INSERT.matcher(this.sql).matches()) {
        return this.client.update(sql, this.bindings.bindings)
            .map(result -> H2Result.toResult(result.getGeneratedKeys(), result.getUpdateCount()));
    } else {
        return this.client.query(sql, this.bindings.bindings)
            .map(result -> H2Result.toResult(result, null));
    }
}
```

H2 throws an exception when `query` is used without a `SELECT` so this will fail for commands like `CREATE TABLE` that exist in Spring Data R2dbc.

Hence, the criteria here should be on `SELECT`.

**Comment by nebhale** [comment]
I swapped this in the other direction intentionally because it was having trouble using `SELECT` as the discriminator. It’s clear that something more sophisticated than either option is required.

**Comment by gregturn** [comment]
What's an example where SELECT fails as the criteria?

In present form, the following test fails, yet passes if we flip the criteria.

```java
@Test
void queryingWithAnUpdate() {

    Mono.from(getConnectionFactory().create())
        .flatMapMany(connection -> {
            Statement statement = connection.createStatement("CREATE TABLE test2 (id SERIAL PRIMARY KEY, value INTEGER)");

            return Flux.from(statement
                .execute())
                .concatWith(close(connection));
        })
        .as(StepVerifier::create)
        .expectNextCount(1)
        .verifyComplete();
}
```

**Comment by nebhale** [comment]
`SHOW TABLES`

```
Caused by: org.h2.jdbc.JdbcSQLException: Method is not allowed for a query. Use execute or executeQuery instead of executeUpdate; SQL statement:
SHOW TABLES [90001-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
```

I figure a lot of the DDL is a candidate for choosing incorrectly.  Wonder if we can even come up with a solid heuristic here.

**Comment by gregturn** [comment]
Looks like we need a fleet of tests and perhaps a three-way if statement.

**Comment by nebhale** [comment]
Agreed.  It'd be great if [this list](http://www.h2database.com/html/grammar.html) indicated what should be used when 😄

**Comment by rotilho** [comment]
There also other criteria like MERGE from H2 which behaviours like INSERT

**Comment by nebhale** [comment]
@rotilho Yep, that’s on the SQL grammar list.

**Comment by gavares** [comment]
The regex for `SELECT` mentioned above as defined in `io.r2dbc.h2.client.Client`:
```scala
    Pattern SELECT = Pattern.compile(".*SELECT.*", CASE_INSENSITIVE);
```

This pattern does not match multi-line sql statements. Coming from Scala, it's common to use triple quotes to break long sql statements up so that they read more nicely. Because of this, the code in `io.r2dbc.h2.H2Statement.execute` version 1.0.0.M6 will fail to properly identity a multiline SELECT statement and attempt to execute it as an update:

```java
    private static Flux<H2Result> execute(Client client, String sql, Bindings bindings, Codecs codecs) {
        if (!SELECT.matcher(sql).matches()) {
            return client.update(sql, bindings.bindings)
                .map(result -> H2Result.toResult(result.getGeneratedKeys(), result.getUpdateCount(), codecs));
        } else {
            return client.query(sql, bindings.bindings)
                .map(result -> H2Result.toResult(result, null, codecs));
        }
    }
```

The `SELECT` pattern can be made to match multiple lines if it is changed to the following:
```java
   Pattern SELECT = Pattern.compile("(?s).*SELECT.*", CASE_INSENSITIVE);
```

**Comment by gavares** [comment]
I've submitted #25 as a temporary workaround although I think there are some larger problems with the general approach being used to determine the type of query that is being executed.

I think rather than attempting to parse sql queries via regex, the code should find another mechanism for determining which jdbc method to invoke. 2 ideas that come to mind:

1. Make use of a proper SQL parsing library
1. Find a way to make use of the R2dbc client method and objects to determine the statement type

The first option seems like it could incur unnecessary dependencies and could end up causing library conflicts.

I don't know the R2dbc SPI well enough to know if the 2nd option is viable, but the idea is that we should already know the nature of the statement passed into the Client by virtue of the user code doing the following:

```scala
    r2dbc.withHandle(h => h.execute(....))
    r2dbc.withHandle(h => h.createUpdate(....))
    r2dbc.withHandle(h => h.select("SELECT ...."))
```
Hopefully this information isn't lost before it reaches the H2 client implementation.

**Comment by gregturn** [comment]
r2dbc-H2 can’t know anything about r2dbc-client. 

However if you’re suggesting we define an SPI enum demarking inserts vs queries and push the responsibility up to clients, that does intrigue me. 

Add something to the SPI that allows you to push something to all clients. After all it’s spring data r2dbc that has dialect support. And I’d rather not introduce dialect support into r2dbc-H2. 

Thoughts @nebhale?

**Comment by gavares** [comment]
Sorry @gregturn , I was misusing terms above. I think your 2nd sentence sounds like what I was suggesting wrt taking advantage of information captured at the client interface:

> However if you’re suggesting we define an SPI enum demarking inserts vs queries and push the responsibility up to clients, that does intrigue me.

Since the Handle object provides methods specific to the sort of query being issued (execute, createUpdate, select), that information could be captured, passed to the vendor specific drivers and the driver could use that information to determine how to handle a given statement. 

It would be the user's responsibility to match the proper handle methods with the supplied sql statement. That really doesn't seem that bad for a library that operates at this level.

It seems to me the only other alternatives are to either leverage a SQL parser library to analyze the query or to provide a higher level SQL DSL like jooq or Slick.

**Comment by nebhale** [comment]
This is absolutely a client-implementation-specific issue and needs to be handled there.  To wit, none of the other existing implementations have different frames depending on what is contained within the SQL statement.  H2 is the only database (so far) that needs to call two different APIs depending on what the user passes in (hell, using the H2 API directly would _force a user_ to know which API to call for every statement it makes).  I believe that [my earlier statement](
https://github.com/r2dbc/r2dbc-h2/issues/9#issuecomment-429919506) still stands.  You're going to have to go through the grammar on a case-by-case basis and establish which SQL keywords are going to require which API invocation.

**Comment by gregturn** [comment]
Basically, we/I must knuckle down and write a barrage of test cases for every single statement and back the solution into that.

**Comment by schauder** [comment]
additional cases to consider:
* "select" as part of column name, table name or alias
* "select" as part of a String literal.
* subselects in where clause or value expression or inline views (I'm not sure if H2 actually supports these)

**Comment by gregturn** [comment]
With https://github.com/r2dbc/r2dbc-h2/commit/232c472ea3b57dd7ae227aa8d0cd742ce96ea5fb committed to master, this issue is retooled to collect test cases for the various permutations of SQL so we can make the client better handle selecting the right H2 API.

**Comment by katzyn** [comment]
> using the H2 API directly would force a user to know which API to call for every statement it makes

It's not an API. It's an internal part of H2 that isn't intended for usage outside of H2 and each new version of H2 may change anything in it without a warning.

H2's implementations of `Statement.execute(String)` and `PreparedStatement.execute()` do not require end user to know whether SQL statement is a query or not.

I suggest you to check value of `CommandInterface.isQuery()` instead of unreliable own checks. There are too many queries (`SELECT`, `TABLE`, `VALUES`) and other commands (`EXPLAIN`, `CALL`, `SCRIPT`) that return a result set. `WITH` and `EXECUTE` return a result set in some situations and return an update count in others.

**Comment by mp911de** [comment]
Thanks a lot @katzyn for having a look. R2DBC H2 is primarily intended as jumpstart for R2DBC apps without spinning up an external server. We haven’t really considered how to proceed in the future. We’re now aware that we’re using internal API and we’ve already seen first tickets about incompatibilities between various versions. 

Would you or Thomas be interested in a conversation regarding our efforts here and whether we can find a mode of development to keep H2 integrated while lowering the risk of regular breaking changes?

**Comment by katzyn** [comment]
> R2DBC H2 is primarily intended as jumpstart for R2DBC apps without spinning up an external server.

But R2DBC-H2 does not allow usage of embedded database, or I'm missing something? Not very nice for starters.

Unfortunately, I don't see a way to use internals safely. There are other projects that use different internals of H2 for own purposes and they all can work only with one exact version of H2 and they upgrade their dependency form time to time with some changes in their code. Perhaps snapshots of R2DBC should explicitly mention supported version of H2 too.

Hypothetically R2DBC driver should be a part of JDBC driver of the database (or an optional standalone part) and their releases should be aligned, but it will be possible only with stable R2DBC specifications. Now they are weak, incomplete, and possibly unstable (just like ADBA), so you need to align releases of R2DBC-H2 with changes in R2DBC.

H2 is not released too often, so for now it's reasonable to update your code to be compatible with latest 1.4.198 and upcoming 1.4.199 (this release is minor and should be more or less compatible with 1.4.198). Note that H2 since 1.4.198 does not allow database creation over TCP by default due to security reasons.

H2 in developed by community and there are no specific future plans, nobody can say what will be changed in the next version. I think you shouldn't care too much about such changes for now.

If you have some questions about H2, feel free to ask them.

**Comment by mp911de** [comment]
From your response, I assume our best approach is to build against the current H2 version and the one that is available from your `master` branch to keep us on the safe side.

> But R2DBC-H2 does not allow usage of embedded database, or I'm missing something? Not very nice for starters.

Actually, the main use case [is embedded](https://github.com/r2dbc/r2dbc-h2/#usage) usage for R2DBC by leveraging the `mem` storage.

```
ConnectionFactory connectionFactory = new H2ConnectionFactory(H2ConnectionConfiguration.builder()
    .inMemory("...")
    .build());
```

Let's revisit the topic of where R2DBC-H2 is hosted once we have a stable and released R2DBC spec.

Thanks a lot @katzyn.

**Comment by gregturn** [comment]
@katzyn Our [CI](https://ci.spring.io/teams/r2dbc/pipelines/r2dbc) pipeline could easily to adjusted to 

* Test against the released version in Maven Central.
* Test against H2's `master` branch.

Each done through a different maven profile.

The one thing that makes that tricky is it appears `pom.xml` is still hovering at `1.4.197-SNAPSHOT` when it probably needs to be at `1.4.199-SNAPSHOT`. (I'm happy to submit a PR if you need one)

**Comment by katzyn** [comment]
@gregturn
Maven-based build of H2 is experimental, buggy and unsupported. It generates larger jar without help, without OSGi attributes and with possible other defects. It may work in your unit tests, however.

The only one correct way to build H2 is documented here:
http://www.h2database.com/html/build.html#building
JDK 7 is used in official builds, but you can use newer versions too if you don't need backward compatibility.

However, thanks for the pointer. We need to update its version too during the release process.
